require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe VoxelsController do

  # This should return the minimal set of attributes required to create a valid
  # Voxel. As you add validations to Voxel, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "user_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # VoxelsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all voxels as @voxels" do
      voxel = Voxel.create! valid_attributes
      get :index, {}, valid_session
      assigns(:voxels).should eq([voxel])
    end
  end

  describe "GET show" do
    it "assigns the requested voxel as @voxel" do
      voxel = Voxel.create! valid_attributes
      get :show, {:id => voxel.to_param}, valid_session
      assigns(:voxel).should eq(voxel)
    end
  end

  describe "GET new" do
    it "assigns a new voxel as @voxel" do
      get :new, {}, valid_session
      assigns(:voxel).should be_a_new(Voxel)
    end
  end

  describe "GET edit" do
    it "assigns the requested voxel as @voxel" do
      voxel = Voxel.create! valid_attributes
      get :edit, {:id => voxel.to_param}, valid_session
      assigns(:voxel).should eq(voxel)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Voxel" do
        expect {
          post :create, {:voxel => valid_attributes}, valid_session
        }.to change(Voxel, :count).by(1)
      end

      it "assigns a newly created voxel as @voxel" do
        post :create, {:voxel => valid_attributes}, valid_session
        assigns(:voxel).should be_a(Voxel)
        assigns(:voxel).should be_persisted
      end

      it "redirects to the created voxel" do
        post :create, {:voxel => valid_attributes}, valid_session
        response.should redirect_to(Voxel.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved voxel as @voxel" do
        # Trigger the behavior that occurs when invalid params are submitted
        Voxel.any_instance.stub(:save).and_return(false)
        post :create, {:voxel => { "user_id" => "invalid value" }}, valid_session
        assigns(:voxel).should be_a_new(Voxel)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Voxel.any_instance.stub(:save).and_return(false)
        post :create, {:voxel => { "user_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested voxel" do
        voxel = Voxel.create! valid_attributes
        # Assuming there are no other voxels in the database, this
        # specifies that the Voxel created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Voxel.any_instance.should_receive(:update).with({ "user_id" => "1" })
        put :update, {:id => voxel.to_param, :voxel => { "user_id" => "1" }}, valid_session
      end

      it "assigns the requested voxel as @voxel" do
        voxel = Voxel.create! valid_attributes
        put :update, {:id => voxel.to_param, :voxel => valid_attributes}, valid_session
        assigns(:voxel).should eq(voxel)
      end

      it "redirects to the voxel" do
        voxel = Voxel.create! valid_attributes
        put :update, {:id => voxel.to_param, :voxel => valid_attributes}, valid_session
        response.should redirect_to(voxel)
      end
    end

    describe "with invalid params" do
      it "assigns the voxel as @voxel" do
        voxel = Voxel.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Voxel.any_instance.stub(:save).and_return(false)
        put :update, {:id => voxel.to_param, :voxel => { "user_id" => "invalid value" }}, valid_session
        assigns(:voxel).should eq(voxel)
      end

      it "re-renders the 'edit' template" do
        voxel = Voxel.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Voxel.any_instance.stub(:save).and_return(false)
        put :update, {:id => voxel.to_param, :voxel => { "user_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested voxel" do
      voxel = Voxel.create! valid_attributes
      expect {
        delete :destroy, {:id => voxel.to_param}, valid_session
      }.to change(Voxel, :count).by(-1)
    end

    it "redirects to the voxels list" do
      voxel = Voxel.create! valid_attributes
      delete :destroy, {:id => voxel.to_param}, valid_session
      response.should redirect_to(voxels_url)
    end
  end

end
